# Site settings
title: Shiban Lal
name: Data Analyst
email: f/xannzajo
url: https://github.com/shiban1503
description: "Data Analyst specializing in Python, SQL, and Data Visualization."
keywords: "data analyst, python, sql, machine learning, data science, analytics"
skills: "Excel | Python | SQL | Machine Learning | Tableau | Power BI"
meta_author: Lal Mohamed Shiban

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: Shiban

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Mohamed Shiban Lal
  # location: Location
  social: Around the Web
  # credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/mohamedshibanlal/
  - title: github
    url: http://github.com/shiban1503

# # Postal address (add as many lines as necessary)
# address:
#   - line: 23 Green Pond Close
#   - line: E17 6EE, London
#   - line: United Kingdom

# Credits content
# credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
